### ISSUE TITLE
ls -l lists everything as directories

### ISSUE THREAD

**Issue by Monarchz3ro** [Monarchz3ro/Silver#3]
when fixing this, if possible, make directories not show anything as their size too. as in not 0, but literally blank

**Comment by OcelotWalrus** [comment]
Why not? Me, I'd make so that displaying the size of the directory actually work. And also make directories names bold or with a '/' at the end so they can be distinguished from files.

And also display the number of content in the current directory.
![image](https://github.com/Monarchz3ro/Silver/assets/87318892/9cb38a78-f420-4e0c-afb3-c43964ae9c1e)

**Comment by Monarchz3ro** [comment]
You've got a point, aye, so do you suggest calculating the size of the directory *as* `ls -l` is working?

**Comment by OcelotWalrus** [comment]
Yes. And all the other things I've said. I can do that.
I've done some changes to your code and I'm gonna make a PR. I've fixed some issues.

By the way, cool project!

**Comment by Monarchz3ro** [comment]
Hey! Thanks, man, really appreciate it!

**Comment by OcelotWalrus** [comment]
You're welcome! I've created my PR (#7)
